### ISSUE TITLE
Back-end de alguns botões

### ISSUE THREAD

**Issue by georgerodriguex** [LeonardoCarneiroArruda/minhasentregas#32]
Ajeitar o botão "Cancelar Viagem" do "transportador_home.php"
Ajeitar o botão de "Recusar", para recusar Encomenda Pendentes do "transportador_home.php"
Ajeitar o botão de "Cancelar solicitação" do "cliente_home.php"

Adoro vocês amigos @Luis-Filho @LeonardoCarneiroArruda 

Como dizia Chaves:
> Prefiro morrer do que perder a vida

**Comment by LeonardoCarneiroArruda** [comment]
Feito, meu caro!
